// Code generated by goctl. DO NOT EDIT.
package types

type DemoError_Request struct {
	SystemStatusCode int    `json:"system_status_code"`
	HTTPStatusCode   int    `json:"http_status_code"`
	Message          string `json:"message"`
}

type DemoError_Response struct {
}

type Manager_Admin_Demo_Request struct {
}

type Manager_Admin_Demo_Response struct {
}

type Client_User_EnterRoom_Request struct {
}

type Client_User_EnterRoom_Response struct {
}
