#!/bin/sh

if test -z "$1"
then
  echo "need target"
else
  # 目标文件
  target=$1

  # 根据进程名结束进程
  process=`ps -ef|grep $target|grep -v grep|grep -v PPID|awk '{ print $2}'`
  for i in $process
  do
    echo "Kill the $target process [ $i ]"
    kill -9 $i
  done

  # 输出反馈
  echo "$target is stopped."
fi
