// Code generated by goctl. DO NOT EDIT.

export interface Request {
}

export interface Response {
}

export interface AdminSelfGetUserListResponse {
  list: Array<AdminSelfGetUserListItem>
}

export interface AdminSelfGetUserListItem {
  id: number
  name: string
  account: string
  password: string
  last_signin_at: number
  created_at: number
  updated_at: number
}

