// Code generated by goctl. DO NOT EDIT.

export interface Client_Public_GetSignUpCaptcha_Request {
}

export interface Client_Public_GetSignUpCaptcha_Response {
}

export interface Client_Public_CheckSignUpCaptcha_Request {
}

export interface Client_Public_CheckSignUpCaptcha_Response {
}

export interface Client_Public_SignUpAccount_Request {
  account: string // 账号
  password: string // 密码（前端加密后提交）
  captcha_code: string // 图形验证码
}

export interface Client_Public_SignUpAccount_Response {
  token: string
}

export interface Client_Public_SignUpMobile_Request {
  country_code: string // 国际区号
  mobile: string // 手机号码
  sms_code: string // 短信验证码
}

export interface Client_Public_SignUpMobile_Response {
  token: string
}

export interface Client_Public_SendSignUpSMS_Request {
  country_code: string // 国际区号
  mobile: string // 手机号码
  captcha_code: string // 图形验证码
}

export interface Client_Public_SendSignUpSMS_Response {
  exp_timestamp: string // 短信验证码有效期时间戳
  remaining_retries: string // 输入错误剩余重试次数
}

export interface Client_Public_GetSignInCaptcha_Request {
}

export interface Client_Public_GetSignInCaptcha_Response {
}

export interface Client_Public_CheckSignInCaptcha_Request {
}

export interface Client_Public_CheckSignInCaptcha_Response {
}

export interface Client_Public_SignInAccount_Request {
  account: string // 账号
  password: string // 密码（前端加密后提交）
  captcha_code: string // 图形验证码
}

export interface Client_Public_SignInAccount_Response {
  token: string
}

export interface Client_Public_SignInMobile_Request {
  country_code: string // 国际区号
  mobile: string // 手机号码
  sms_code: string // 短信验证码
}

export interface Client_Public_SignInMobile_Response {
  token: string
}

export interface Client_Public_SendSignInSMS_Request {
  country_code: string // 国际区号
  mobile: string // 手机号码
  captcha_code: string // 图形验证码
}

export interface Client_Public_SendSignInSMS_Response {
  exp_timestamp: string // 短信验证码有效期时间戳
  remaining_retries: string // 输入错误剩余重试次数
}

export interface Manager_Admin_GetUserList_Request {
}
export interface Manager_Admin_GetUserList_RequestParams {
  page: number // 当前页码
  per_page: number // 每页条目
  order_column: string // 排序字段
  order_type: string // 排序类型，asc、desc
  search_account_like: string // 账号
}

export interface Manager_Admin_GetUserList_Response {
  total: number
  items: Array<Manager_Admin_GetUserList_Response_Item>
}

export interface Manager_Admin_GetUserList_Response_Item {
  id: number // 用户 ID
  name: string // 名称
  account: string // 账号
  created_at: number // 创建时间
  last_signin_at: number // 上次登录时间
}

export interface Manager_Admin_GetUserInfo_Request {
}
export interface Manager_Admin_GetUserInfo_RequestParams {
}

export interface Manager_Admin_GetUserInfo_Response {
  id: number // 用户 ID
  name: string // 名称
  account: string // 账号
  created_at: number // 创建时间
  last_signin_at: number // 上次登录时间
}

