// Code generated by goctl. DO NOT EDIT.

import { instance as http } from "./apiRequester"
import { AxiosRequestConfig } from "axios"
import qs from "qs"
import * as components from "./userComponents"
export * from "./userComponents"

/**
 * @description 获取用户列表
 */
export function manager_admin_getUserList(config?: AxiosRequestConfig) {
  return http.get<components.AdminSelfGetUserListResponse>(`manager/admin/users`, config)
}

/**
 * @description 获取用户详情
 */
export function manager_admin_getUserInfo(config?: AxiosRequestConfig) {
  return http.get<components.Response>(`manager/admin/users/${id}`, config)
}
