// Code generated by goctl. DO NOT EDIT.
// Source: admin.proto

package adminclient

import (
	"context"

	"github.com/zero-vue-demo/app-center-public/rpc/admin"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CheckToken_Request   = admin.CheckToken_Request
	CheckToken_Response  = admin.CheckToken_Response
	DeleteToken_Request  = admin.DeleteToken_Request
	DeleteToken_Response = admin.DeleteToken_Response
	MakeToken_Request    = admin.MakeToken_Request
	MakeToken_Response   = admin.MakeToken_Response

	Admin interface {
		// 生成 token（登录）
		MakeToken(ctx context.Context, in *MakeToken_Request, opts ...grpc.CallOption) (*MakeToken_Response, error)
		// 校验 token（拓展校验、刷新 token）
		CheckToken(ctx context.Context, in *CheckToken_Request, opts ...grpc.CallOption) (*CheckToken_Response, error)
		// 移除 token（安全退出）
		DeleteToken(ctx context.Context, in *DeleteToken_Request, opts ...grpc.CallOption) (*DeleteToken_Response, error)
	}

	defaultAdmin struct {
		cli zrpc.Client
	}
)

func NewAdmin(cli zrpc.Client) Admin {
	return &defaultAdmin{
		cli: cli,
	}
}

// 生成 token（登录）
func (m *defaultAdmin) MakeToken(ctx context.Context, in *MakeToken_Request, opts ...grpc.CallOption) (*MakeToken_Response, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.MakeToken(ctx, in, opts...)
}

// 校验 token（拓展校验、刷新 token）
func (m *defaultAdmin) CheckToken(ctx context.Context, in *CheckToken_Request, opts ...grpc.CallOption) (*CheckToken_Response, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.CheckToken(ctx, in, opts...)
}

// 移除 token（安全退出）
func (m *defaultAdmin) DeleteToken(ctx context.Context, in *DeleteToken_Request, opts ...grpc.CallOption) (*DeleteToken_Response, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.DeleteToken(ctx, in, opts...)
}
