// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"app/com.docker.devenvironments.code/public/rpc/user"
	"app/user/rpc/internal/logic"
	"app/user/rpc/internal/svc"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

// 生成 token（登录）
func (s *UserServer) MakeToken(ctx context.Context, in *user.MakeToken_Request) (*user.MakeToken_Response, error) {
	l := logic.NewMakeTokenLogic(ctx, s.svcCtx)
	return l.MakeToken(in)
}

// 校验 token（拓展校验、刷新 token）
func (s *UserServer) CheckToken(ctx context.Context, in *user.CheckToken_Request) (*user.CheckToken_Response, error) {
	l := logic.NewCheckTokenLogic(ctx, s.svcCtx)
	return l.CheckToken(in)
}

// 移除 token（安全退出）
func (s *UserServer) DeleteToken(ctx context.Context, in *user.DeleteToken_Request) (*user.DeleteToken_Response, error) {
	l := logic.NewDeleteTokenLogic(ctx, s.svcCtx)
	return l.DeleteToken(in)
}
