// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	api "app/chatroom/api/internal/handler/api"
	clientpublic "app/chatroom/api/internal/handler/client/public"
	clientuser "app/chatroom/api/internal/handler/client/user"
	manageradmin "app/chatroom/api/internal/handler/manager/admin"
	"app/chatroom/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: api.NothingHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/demo/error",
				Handler: api.DemoErrorHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/doc/swagger",
				Handler: api.SwaggerDocHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthAdminMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/demo",
					Handler: manageradmin.DemoHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/manager/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/ws",
				Handler: clientpublic.WsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/client/public"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthUserMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/rooms/:id",
					Handler: clientuser.EnterRoomHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/client/user"),
	)
}
