// Code generated by goctl. DO NOT EDIT.
// Source: admin.proto

package server

import (
	"context"

	"app/admin/rpc/internal/logic"
	"app/admin/rpc/internal/svc"
	"github.com/zero-vue-demo/app-center-public/rpc/admin"
)

type AdminServer struct {
	svcCtx *svc.ServiceContext
	admin.UnimplementedAdminServer
}

func NewAdminServer(svcCtx *svc.ServiceContext) *AdminServer {
	return &AdminServer{
		svcCtx: svcCtx,
	}
}

// 生成 token（登录）
func (s *AdminServer) MakeToken(ctx context.Context, in *admin.MakeToken_Request) (*admin.MakeToken_Response, error) {
	l := logic.NewMakeTokenLogic(ctx, s.svcCtx)
	return l.MakeToken(in)
}

// 校验 token（拓展校验、刷新 token）
func (s *AdminServer) CheckToken(ctx context.Context, in *admin.CheckToken_Request) (*admin.CheckToken_Response, error) {
	l := logic.NewCheckTokenLogic(ctx, s.svcCtx)
	return l.CheckToken(in)
}

// 移除 token（安全退出）
func (s *AdminServer) DeleteToken(ctx context.Context, in *admin.DeleteToken_Request) (*admin.DeleteToken_Response, error) {
	l := logic.NewDeleteTokenLogic(ctx, s.svcCtx)
	return l.DeleteToken(in)
}
